### PR TITLE
Update lint checks for 32-bit Windows. Fixes #16.

### LINKED ISSUE #16: failed on 32-bit tests
https://ci.appveyor.com/project/MaidSafe-QA/memory-map/build/1.0.5

### PR DESCRIPTION
**Pull request by s-brian**

### CODE REVIEW

**Comment by s-brian** [comment]
@Fraser999 The easiest option here was to allow trivial numeric/casts until a better alternative is found.

**Comment by Fraser999** [comment]
@s-brian I've created PR https://github.com/maidsafe/memory_map/pull/18 which includes the commit from this one.  I think it's best to try and limit the scope of the `#allow[(...)]`s as far as possible, so I removed the project-wide instances and made them file-scope or function-scope.  Some weren't needed at all.

**Comment by s-brian** [comment]
Cheers @Fraser999.

**Pull request merged**
