### PR TITLE
Adds lint checks. Fixes #11.

### LINKED ISSUE #11: Missing lint checks
This project is missing the standard set of lint checks we use.

### PR DESCRIPTION
**Pull request by s-brian**

### CODE REVIEW

**Comment by dirvine** [comment]
Looks good, we will need a crates publish PR I think after this is merged.

**Comment by s-brian** [comment]
The appveyor build failed to trigger.

**Comment by dirvine** [comment]
Is it OK locally in Windows?

**Comment by Fraser999** [comment]
The build ran on Appveyor, but it hasn't updated GitHub.

It passed on 64-bit, failed on 32-bit: https://ci.appveyor.com/project/MaidSafe-QA/memory-map/build/1.0.5

**Comment by dirvine** [comment]
Should we leave it open to fix the u32 issue perhaps?

**Comment by Fraser999** [comment]
I guess either that or merge this and create a new issue?  I don't mind, as long as it doesn't get forgotten :)

**Pull request merged**
